version: "3"

services:
  api:
    build: ./api-gateway
    ports:
      - "3333:3333"
    container_name: blog-api

  client:
    build: ./web
    ports:
      - "80:80"
    container_name: blog-client
